#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    #-----------------ONLY IF NUMERICAL VALUE IS NOT THERE-----------
    # return s.title()
    
    
    #--------------ONLY CAN BE USED IF SPACE IS CONSISTENT----------------------
    # a=[]
    # b= s.split()
    # for char in b:
    #     a.append(char.capitalize())
    
    # return ' '.join(a)
    
    result = ''
    
    for i in range(len(s)):
        if i==0 or s[i-1]==' ':
            result += s[i].upper()
        else:
            result += s[i]
    return result
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
